// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/artnikel/subservice/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Create(ctx context.Context, subscription *models.Subscription) error {
	ret := _mock.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Subscription) error); ok {
		r0 = returnFunc(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - subscription
func (_e *MockSubscriptionRepository_Expecter) Create(ctx interface{}, subscription interface{}) *MockSubscriptionRepository_Create_Call {
	return &MockSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, subscription)}
}

func (_c *MockSubscriptionRepository_Create_Call) Run(run func(ctx context.Context, subscription *models.Subscription)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) Return(err error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, subscription *models.Subscription) error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockSubscriptionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSubscriptionRepository_Delete_Call {
	return &MockSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSubscriptionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) Return(err error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Subscription, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Subscription, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Subscription); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubscriptionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockSubscriptionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSubscriptionRepository_GetByID_Call {
	return &MockSubscriptionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSubscriptionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) Return(subscription *models.Subscription, err error) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.Subscription, error)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCostSummary provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) GetCostSummary(ctx context.Context, userID *uuid.UUID, serviceName *string, startMonth string, endMonth string) (int, error) {
	ret := _mock.Called(ctx, userID, serviceName, startMonth, endMonth)

	if len(ret) == 0 {
		panic("no return value specified for GetCostSummary")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *string, string, string) (int, error)); ok {
		return returnFunc(ctx, userID, serviceName, startMonth, endMonth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *string, string, string) int); ok {
		r0 = returnFunc(ctx, userID, serviceName, startMonth, endMonth)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, *string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, serviceName, startMonth, endMonth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_GetCostSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCostSummary'
type MockSubscriptionRepository_GetCostSummary_Call struct {
	*mock.Call
}

// GetCostSummary is a helper method to define mock.On call
//   - ctx
//   - userID
//   - serviceName
//   - startMonth
//   - endMonth
func (_e *MockSubscriptionRepository_Expecter) GetCostSummary(ctx interface{}, userID interface{}, serviceName interface{}, startMonth interface{}, endMonth interface{}) *MockSubscriptionRepository_GetCostSummary_Call {
	return &MockSubscriptionRepository_GetCostSummary_Call{Call: _e.mock.On("GetCostSummary", ctx, userID, serviceName, startMonth, endMonth)}
}

func (_c *MockSubscriptionRepository_GetCostSummary_Call) Run(run func(ctx context.Context, userID *uuid.UUID, serviceName *string, startMonth string, endMonth string)) *MockSubscriptionRepository_GetCostSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID), args[2].(*string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetCostSummary_Call) Return(n int, err error) *MockSubscriptionRepository_GetCostSummary_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSubscriptionRepository_GetCostSummary_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, serviceName *string, startMonth string, endMonth string) (int, error)) *MockSubscriptionRepository_GetCostSummary_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) List(ctx context.Context, userID *uuid.UUID, serviceName *string, page int, pageSize int) ([]models.Subscription, int, error) {
	ret := _mock.Called(ctx, userID, serviceName, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Subscription
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *string, int, int) ([]models.Subscription, int, error)); ok {
		return returnFunc(ctx, userID, serviceName, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *string, int, int) []models.Subscription); ok {
		r0 = returnFunc(ctx, userID, serviceName, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, *string, int, int) int); ok {
		r1 = returnFunc(ctx, userID, serviceName, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *uuid.UUID, *string, int, int) error); ok {
		r2 = returnFunc(ctx, userID, serviceName, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSubscriptionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubscriptionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx
//   - userID
//   - serviceName
//   - page
//   - pageSize
func (_e *MockSubscriptionRepository_Expecter) List(ctx interface{}, userID interface{}, serviceName interface{}, page interface{}, pageSize interface{}) *MockSubscriptionRepository_List_Call {
	return &MockSubscriptionRepository_List_Call{Call: _e.mock.On("List", ctx, userID, serviceName, page, pageSize)}
}

func (_c *MockSubscriptionRepository_List_Call) Run(run func(ctx context.Context, userID *uuid.UUID, serviceName *string, page int, pageSize int)) *MockSubscriptionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID), args[2].(*string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockSubscriptionRepository_List_Call) Return(subscriptions []models.Subscription, n int, err error) *MockSubscriptionRepository_List_Call {
	_c.Call.Return(subscriptions, n, err)
	return _c
}

func (_c *MockSubscriptionRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, serviceName *string, page int, pageSize int) ([]models.Subscription, int, error)) *MockSubscriptionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Update(ctx context.Context, id uuid.UUID, updates *models.SubscriptionUpdates) (*models.Subscription, error) {
	ret := _mock.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.SubscriptionUpdates) (*models.Subscription, error)); ok {
		return returnFunc(ctx, id, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.SubscriptionUpdates) *models.Subscription); ok {
		r0 = returnFunc(ctx, id, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *models.SubscriptionUpdates) error); ok {
		r1 = returnFunc(ctx, id, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx
//   - id
//   - updates
func (_e *MockSubscriptionRepository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *MockSubscriptionRepository_Update_Call {
	return &MockSubscriptionRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *MockSubscriptionRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, updates *models.SubscriptionUpdates)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*models.SubscriptionUpdates))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) Return(subscription *models.Subscription, err error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, updates *models.SubscriptionUpdates) (*models.Subscription, error)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
