// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/artnikel/subservice/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionService creates a new instance of MockSubscriptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionService {
	mock := &MockSubscriptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionService is an autogenerated mock type for the SubscriptionService type
type MockSubscriptionService struct {
	mock.Mock
}

type MockSubscriptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionService) EXPECT() *MockSubscriptionService_Expecter {
	return &MockSubscriptionService_Expecter{mock: &_m.Mock}
}

// CreateSubscription provides a mock function for the type MockSubscriptionService
func (_mock *MockSubscriptionService) CreateSubscription(ctx context.Context, req *models.CreateSubscriptionRequest) (*models.Subscription, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 *models.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateSubscriptionRequest) (*models.Subscription, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateSubscriptionRequest) *models.Subscription); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.CreateSubscriptionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionService_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MockSubscriptionService_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockSubscriptionService_Expecter) CreateSubscription(ctx interface{}, req interface{}) *MockSubscriptionService_CreateSubscription_Call {
	return &MockSubscriptionService_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctx, req)}
}

func (_c *MockSubscriptionService_CreateSubscription_Call) Run(run func(ctx context.Context, req *models.CreateSubscriptionRequest)) *MockSubscriptionService_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateSubscriptionRequest))
	})
	return _c
}

func (_c *MockSubscriptionService_CreateSubscription_Call) Return(subscription *models.Subscription, err error) *MockSubscriptionService_CreateSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionService_CreateSubscription_Call) RunAndReturn(run func(ctx context.Context, req *models.CreateSubscriptionRequest) (*models.Subscription, error)) *MockSubscriptionService_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscription provides a mock function for the type MockSubscriptionService
func (_mock *MockSubscriptionService) DeleteSubscription(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionService_DeleteSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscription'
type MockSubscriptionService_DeleteSubscription_Call struct {
	*mock.Call
}

// DeleteSubscription is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockSubscriptionService_Expecter) DeleteSubscription(ctx interface{}, id interface{}) *MockSubscriptionService_DeleteSubscription_Call {
	return &MockSubscriptionService_DeleteSubscription_Call{Call: _e.mock.On("DeleteSubscription", ctx, id)}
}

func (_c *MockSubscriptionService_DeleteSubscription_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionService_DeleteSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionService_DeleteSubscription_Call) Return(err error) *MockSubscriptionService_DeleteSubscription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionService_DeleteSubscription_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSubscriptionService_DeleteSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetCostSummary provides a mock function for the type MockSubscriptionService
func (_mock *MockSubscriptionService) GetCostSummary(ctx context.Context, req *models.CostSummaryRequest) (*models.CostSummaryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetCostSummary")
	}

	var r0 *models.CostSummaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CostSummaryRequest) (*models.CostSummaryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CostSummaryRequest) *models.CostSummaryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CostSummaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.CostSummaryRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionService_GetCostSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCostSummary'
type MockSubscriptionService_GetCostSummary_Call struct {
	*mock.Call
}

// GetCostSummary is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockSubscriptionService_Expecter) GetCostSummary(ctx interface{}, req interface{}) *MockSubscriptionService_GetCostSummary_Call {
	return &MockSubscriptionService_GetCostSummary_Call{Call: _e.mock.On("GetCostSummary", ctx, req)}
}

func (_c *MockSubscriptionService_GetCostSummary_Call) Run(run func(ctx context.Context, req *models.CostSummaryRequest)) *MockSubscriptionService_GetCostSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CostSummaryRequest))
	})
	return _c
}

func (_c *MockSubscriptionService_GetCostSummary_Call) Return(costSummaryResponse *models.CostSummaryResponse, err error) *MockSubscriptionService_GetCostSummary_Call {
	_c.Call.Return(costSummaryResponse, err)
	return _c
}

func (_c *MockSubscriptionService_GetCostSummary_Call) RunAndReturn(run func(ctx context.Context, req *models.CostSummaryRequest) (*models.CostSummaryResponse, error)) *MockSubscriptionService_GetCostSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscription provides a mock function for the type MockSubscriptionService
func (_mock *MockSubscriptionService) GetSubscription(ctx context.Context, id uuid.UUID) (*models.Subscription, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 *models.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Subscription, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Subscription); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionService_GetSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscription'
type MockSubscriptionService_GetSubscription_Call struct {
	*mock.Call
}

// GetSubscription is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockSubscriptionService_Expecter) GetSubscription(ctx interface{}, id interface{}) *MockSubscriptionService_GetSubscription_Call {
	return &MockSubscriptionService_GetSubscription_Call{Call: _e.mock.On("GetSubscription", ctx, id)}
}

func (_c *MockSubscriptionService_GetSubscription_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubscriptionService_GetSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionService_GetSubscription_Call) Return(subscription *models.Subscription, err error) *MockSubscriptionService_GetSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionService_GetSubscription_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.Subscription, error)) *MockSubscriptionService_GetSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubscriptions provides a mock function for the type MockSubscriptionService
func (_mock *MockSubscriptionService) ListSubscriptions(ctx context.Context, userID *uuid.UUID, serviceName *string, page int, pageSize int) (*models.ListResponse, error) {
	ret := _mock.Called(ctx, userID, serviceName, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListSubscriptions")
	}

	var r0 *models.ListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *string, int, int) (*models.ListResponse, error)); ok {
		return returnFunc(ctx, userID, serviceName, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *string, int, int) *models.ListResponse); ok {
		r0 = returnFunc(ctx, userID, serviceName, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, *string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, serviceName, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionService_ListSubscriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubscriptions'
type MockSubscriptionService_ListSubscriptions_Call struct {
	*mock.Call
}

// ListSubscriptions is a helper method to define mock.On call
//   - ctx
//   - userID
//   - serviceName
//   - page
//   - pageSize
func (_e *MockSubscriptionService_Expecter) ListSubscriptions(ctx interface{}, userID interface{}, serviceName interface{}, page interface{}, pageSize interface{}) *MockSubscriptionService_ListSubscriptions_Call {
	return &MockSubscriptionService_ListSubscriptions_Call{Call: _e.mock.On("ListSubscriptions", ctx, userID, serviceName, page, pageSize)}
}

func (_c *MockSubscriptionService_ListSubscriptions_Call) Run(run func(ctx context.Context, userID *uuid.UUID, serviceName *string, page int, pageSize int)) *MockSubscriptionService_ListSubscriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID), args[2].(*string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockSubscriptionService_ListSubscriptions_Call) Return(listResponse *models.ListResponse, err error) *MockSubscriptionService_ListSubscriptions_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockSubscriptionService_ListSubscriptions_Call) RunAndReturn(run func(ctx context.Context, userID *uuid.UUID, serviceName *string, page int, pageSize int) (*models.ListResponse, error)) *MockSubscriptionService_ListSubscriptions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSubscription provides a mock function for the type MockSubscriptionService
func (_mock *MockSubscriptionService) UpdateSubscription(ctx context.Context, id uuid.UUID, req *models.UpdateSubscriptionRequest) (*models.Subscription, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 *models.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.UpdateSubscriptionRequest) (*models.Subscription, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.UpdateSubscriptionRequest) *models.Subscription); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *models.UpdateSubscriptionRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionService_UpdateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSubscription'
type MockSubscriptionService_UpdateSubscription_Call struct {
	*mock.Call
}

// UpdateSubscription is a helper method to define mock.On call
//   - ctx
//   - id
//   - req
func (_e *MockSubscriptionService_Expecter) UpdateSubscription(ctx interface{}, id interface{}, req interface{}) *MockSubscriptionService_UpdateSubscription_Call {
	return &MockSubscriptionService_UpdateSubscription_Call{Call: _e.mock.On("UpdateSubscription", ctx, id, req)}
}

func (_c *MockSubscriptionService_UpdateSubscription_Call) Run(run func(ctx context.Context, id uuid.UUID, req *models.UpdateSubscriptionRequest)) *MockSubscriptionService_UpdateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*models.UpdateSubscriptionRequest))
	})
	return _c
}

func (_c *MockSubscriptionService_UpdateSubscription_Call) Return(subscription *models.Subscription, err error) *MockSubscriptionService_UpdateSubscription_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionService_UpdateSubscription_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, req *models.UpdateSubscriptionRequest) (*models.Subscription, error)) *MockSubscriptionService_UpdateSubscription_Call {
	_c.Call.Return(run)
	return _c
}
